import Footer from "@/components/Footer/Footer";
import MainNav from "@/components/Navbar/MianNav/MainNav";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNav />

        {children}

        <Footer />
      </body>
    </html>
  );
}
